cluster.name: es-cluster
node.name: node-master-01
node.roles: ["master"]
bootstrap.memory_lock: true

network.host: 0.0.0.0
discovery.seed_hosts:
cluster.initial_master_nodes: ["node-master-01"]

xpack.license.self_generated.type: trial
xpack.security.enabled: false
