cluster.name: es-cluster
node.name: node-data-01
node.roles: ["data", "ingest"]
bootstrap.memory_lock: true

network.host: _site_
discovery.seed_hosts: ${ELASTICSEARCH__DISCOVERY__SEED_HOSTS}
cluster.initial_master_nodes: ["node-master-01"]

xpack.license.self_generated.type: trial
xpack.security.enabled: false
