version: '3.8'
services:
  es-master-01:
    container_name: es-master-01
    build:
      context: elasticsearch/docker/
      args:
        ELK_VERSION: ${ELK_VERSION}
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch/config/elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - data01:/usr/share/elasticsearch/data:z
    environment:
      ELASTICSEARCH__DISCOVERY__SEED_HOSTS: "es-master-01,es-data-01"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elastic
    deploy:
      resources:
        limits:
          memory: 1GB

  es-data-01:
    container_name: es-data-01
    build:
      context: elasticsearch/docker/
      args:
        ELK_VERSION: ${ELK_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - data02:/usr/share/elasticsearch/data:z
    environment:
      ELASTICSEARCH__DISCOVERY__SEED_HOSTS: "es-master-01,es-data-01"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elastic
    deploy:
      resources:
        limits:
          memory: 1GB

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    environment:
      ELASTICSEARCH__HOSTS: "http://es-master-01:9200"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - elastic
    depends_on:
      - es-master-01
    deploy:
      resources:
        limits:
          memory: 1GB

networks:
  elastic:
    driver: bridge

volumes:
  data01:
    driver: local
  data02:
    driver: local
